//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InigmaIT.HTML {
    
    
    public partial class CandidateConfirmDeleteAccount {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountHomePageTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountHomePageTopLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountAboutUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountAboutUsTopLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountRegistrationTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountRegistrationTopLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountJobSearchTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountJobSearchTopLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountContactUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountContactUsTopLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountLoginTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountLoginTopLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountOK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CandidateConfirmDeleteAccountOK;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CandidateConfirmDeleteAccountCancel;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountHomePageBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountHomePageBotLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountAboutUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountAboutUsBotLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountRegistrationBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountRegistrationBotLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountJobSearchBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountJobSearchBotLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountContactUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountContactUsBotLink;
        
        /// <summary>
        /// CandidateConfirmDeleteAccountLoginBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmDeleteAccountLoginBotLink;
        
        /// <summary>
        /// lblCandidateConfirmDeleteAccountYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCandidateConfirmDeleteAccountYear;
    }
}
