//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InigmaIT.HTML {
    
    
    public partial class CandidateAccountDeleteConfirmation {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationHomePageTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationHomePageTopLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationAboutUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationAboutUsTopLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationRegistrationTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationRegistrationTopLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationJobSearchTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationJobSearchTopLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationContactUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationContactUsTopLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationLoginTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationLoginTopLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationOK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CandidateAccountDeleteConfirmationOK;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationHomePageBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationHomePageBotLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationAboutUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationAboutUsBotLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationRegistrationBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationRegistrationBotLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationJobSearchBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationJobSearchBotLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationContactUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationContactUsBotLink;
        
        /// <summary>
        /// CandidateAccountDeleteConfirmationLoginBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateAccountDeleteConfirmationLoginBotLink;
        
        /// <summary>
        /// lblCandidateAccountDeleteConfirmationYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCandidateAccountDeleteConfirmationYear;
    }
}
