//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InigmaIT.HTML {
    
    
    public partial class CandidateJobApplicationDeleteConfirmation {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationHomePageTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationHomePageTopLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationAboutUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationAboutUsTopLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationRegistrationTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationRegistrationTopLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationJobSearchTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationJobSearchTopLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationContactUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationContactUsTopLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationLoginTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationLoginTopLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationOK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CandidateJobApplicationDeleteConfirmationOK;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationHomeHomePageBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationHomeHomePageBotLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationHomeAboutUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationHomeAboutUsBotLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationHomeRegistrationBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationHomeRegistrationBotLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationHomeJobSearchBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationHomeJobSearchBotLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationHomeContactUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationHomeContactUsBotLink;
        
        /// <summary>
        /// CandidateJobApplicationDeleteConfirmationHomeLoginBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationDeleteConfirmationHomeLoginBotLink;
        
        /// <summary>
        /// lblCandidateJobApplicationDeleteConfirmationYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCandidateJobApplicationDeleteConfirmationYear;
    }
}
