//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InigmaIT.HTML {
    
    
    public partial class WebForm2 {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteHomePageTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteHomePageTopLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteAboutUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteAboutUsTopLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteRegistrationTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteRegistrationTopLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteJobSearchTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteJobSearchTopLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteContactUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteContactUsTopLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteLoginTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteLoginTopLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteOK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CandidateConfirmJobApplicationDeleteOK;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CandidateConfirmJobApplicationDeleteCancel;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteHomePageBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteHomePageBotLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteAboutUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteAboutUsBotLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteRegistrationBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteRegistrationBotLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteJobSearchBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteJobSearchBotLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteContactUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteContactUsBotLink;
        
        /// <summary>
        /// CandidateConfirmJobApplicationDeleteLoginBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateConfirmJobApplicationDeleteLoginBotLink;
        
        /// <summary>
        /// lblCandidateConfirmJobApplicationDeleteYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCandidateConfirmJobApplicationDeleteYear;
    }
}
