//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InigmaIT.PAGE {
    
    
    public partial class CandidateJobApplications {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// CandidateJobApplicationsHomePageTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsHomePageTopLink;
        
        /// <summary>
        /// CandidateJobApplicationsAboutUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsAboutUsTopLink;
        
        /// <summary>
        /// CandidateJobApplicationsRegistrationTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsRegistrationTopLink;
        
        /// <summary>
        /// CandidateJobApplicationsJobSearchTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsJobSearchTopLink;
        
        /// <summary>
        /// CandidateJobApplicationsContactUsTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsContactUsTopLink;
        
        /// <summary>
        /// CandidateJobApplicationsLoginTopLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsLoginTopLink;
        
        /// <summary>
        /// btnCandidateJobApplicationsDeleteApplication control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCandidateJobApplicationsDeleteApplication;
        
        /// <summary>
        /// btnCandidateJobApplicationsViewJobAppliedFor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCandidateJobApplicationsViewJobAppliedFor;
        
        /// <summary>
        /// CandidateJobApplicationsHomePageBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsHomePageBotLink;
        
        /// <summary>
        /// CandidateJobApplicationsAboutUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsAboutUsBotLink;
        
        /// <summary>
        /// CandidateJobApplicationsRegistrationBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsRegistrationBotLink;
        
        /// <summary>
        /// CandidateJobApplicationsJobSearchBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsJobSearchBotLink;
        
        /// <summary>
        /// CandidateJobApplicationsContactUsBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsContactUsBotLink;
        
        /// <summary>
        /// CandidateJobApplicationsLoginBotLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton CandidateJobApplicationsLoginBotLink;
        
        /// <summary>
        /// lblCandidateJobApplicationsYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCandidateJobApplicationsYear;
    }
}
